name: Coverage Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: coverage build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: rolling
    steps:
      - uses: ros-tooling/setup-ros@0.7.7
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@0.3.5
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          # build all packages listed in the meta package
          package-name:
            odri_bolt_description
            odri_bolt_bringup
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@v3.1.4
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v4.0.0
        with:
          name: colcon-logs-ubuntu-22.04-coverage-rolling
          path: ros_ws/log
