name: ROS Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [lint_cmake, mypy, pep257,  xmllint]
    steps:
    - uses: actions/checkout@v4
    - uses: ros-tooling/setup-ros@0.7.7
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        package-name:
          odri_bolt_description
          odri_bolt_bringup
